"""Platform-specific application engines.

Each platform (Greenhouse, Workday, Lever, etc.) has its own form structure
and API. Platform engines handle the full apply flow: extract job metadata,
map profile fields, fill the form, upload documents, and submit.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from pydantic import BaseModel, Field

from bidcopilot.profile.schemas import UserProfile
from bidcopilot.utils.logging import get_logger

logger = get_logger(__name__)


class JobMetadata(BaseModel):
    """Structured data extracted from a job posting URL."""
    job_id: str
    title: str
    company: str
    location: str = ""
    department: str = ""
    description_html: str = ""
    description_text: str = ""
    employment_type: str = ""
    url: str = ""
    questions: list[dict] = Field(default_factory=list)
    raw: dict = Field(default_factory=dict)


class GeneratedDocuments(BaseModel):
    """Resume + cover letter generated by CVCopilot for a specific job."""
    resume_path: str
    resume_text: str = ""
    cover_letter_path: str | None = None
    cover_letter_text: str | None = None
    filename: str = ""


class BidResult(BaseModel):
    """Outcome of an auto-bid attempt."""
    success: bool
    job_id: str = ""
    job_title: str = ""
    company: str = ""
    confirmation_text: str | None = None
    error: str | None = None
    screenshot_path: str | None = None
    fields_filled: int = 0
    questions_answered: int = 0
    resume_path: str | None = None
    cover_letter_path: str | None = None


class BasePlatformEngine(ABC):
    """ABC for platform-specific auto-bid engines."""

    platform_name: str = "unknown"

    @abstractmethod
    async def extract_job(self, job_url: str) -> JobMetadata:
        """Fetch and parse job posting metadata from the URL."""
        ...

    @abstractmethod
    async def apply(
        self,
        job_url: str,
        profile: UserProfile,
        resume_path: str | None = None,
        cover_letter_path: str | None = None,
        dry_run: bool = False,
    ) -> BidResult:
        """Execute the full application flow for a job posting.

        If ``resume_path`` is None, the engine will generate a tailored
        resume via CVCopilot using the profile and extracted job data.
        """
        ...

    @classmethod
    def can_handle(cls, url: str) -> bool:
        """Return True if this engine can handle the given URL."""
        return False
